In [3]:
#imort numpy library
import numpy as np

In [5]:
x=np.array([15,25,35,45,55,65])
print(x)
print(type(x))
print(x.dtype)

[15 25 35 45 55 65]
<class 'numpy.ndarray'>
int32


In [7]:
x=np.array([75,85,95,48.2])
print(x)
print(type(x))
print(x.dtype)

[75.  85.  95.  48.2]
<class 'numpy.ndarray'>
float64


In [11]:
x=np.array(["B",75,85,95,48.2])
print(x)
print(type(x))
print(x.dtype)

['B' '75' '85' '95' '48.2']
<class 'numpy.ndarray'>
<U32


In [17]:
a2=np.array([[12,22,],[14,24]])
print(a2)
print(type(a2))
print(a2.shape)

[[12 22]
 [14 24]]
<class 'numpy.ndarray'>
(2, 2)


In [25]:
# reshaping an array using reshape()
a=np.array([21,22,23,24])
b=a.reshape(1,4)
print(b)
print(b.shape)

[[21 22 23 24]]
(1, 4)


In [27]:
# create an aarray with arange()
c=np.arange(4,21)
print(c)
type(c)

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


numpy.ndarray

In [29]:
d=np.array([2.645,3.897,7.832])
print(d)
np.around(d,2)

[2.645 3.897 7.832]


array([2.64, 3.9 , 7.83])

In [31]:
d=np.array([2.645,3.897,7.832])
print(d)
print(np.around(np.sqrt(d),2))

[2.645 3.897 7.832]
[1.63 1.97 2.8 ]


In [33]:
a1=np.array([[3,4,5,6],[7,8,9,np.NaN]])
print(a1)
a1.dtype

[[ 3.  4.  5.  6.]
 [ 7.  8.  9. nan]]


dtype('float64')

In [35]:
a1=np.array([[3,4,5,6],[7,8,9,np.NaN]])
a1_copy1=a1.astype(str)
print(a1_copy1)
a1_copy1.dtype

[['3.0' '4.0' '5.0' '6.0']
 ['7.0' '8.0' '9.0' 'nan']]


dtype('<U32')

In [51]:
x=np.array([[3,4,6],[7,9,10],[4,6,12]])

In [55]:
x.sum(axis=1)

array([13, 26, 22])

In [57]:
x.sum(axis=0)

array([14, 19, 28])

In [59]:
y=np.array([[3,4,5],[7,2,8],[9,1,6]])
print(y)

[[3 4 5]
 [7 2 8]
 [9 1 6]]


In [67]:
np.fill_diagonal(y,0)
print(y)

[[0 4 5]
 [7 0 8]
 [9 1 0]]


In [73]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
c=np.matmul(A,B)
print(c)

[[19 22]
 [43 50]]


In [75]:
print(A.T)
print(B.T)

[[1 3]
 [2 4]]
[[5 7]
 [6 8]]


In [77]:
x=np.array([[3,4,5],[6,7,8],[9,3,2],[11,12,13]])
x

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9,  3,  2],
       [11, 12, 13]])

In [79]:
x[2][2]

2

In [81]:
x[1:3,0:2]

array([[6, 7],
       [9, 3]])

In [83]:
x[1:3,0:]

array([[6, 7, 8],
       [9, 3, 2]])

In [85]:
a1=np.array([[3,4,5],[7,2,8],[9,1,6]])
a1

array([[3, 4, 5],
       [7, 2, 8],
       [9, 1, 6]])

In [89]:
print(np.argmax(a1,axis=1))
print(np.argmax(a1,axis=0))

[2 2 0]
[2 0 1]


In [91]:
print(np.max(a1,axis=1))
print(np.max(a1,axis=0))

[5 8 9]
[9 4 8]
